version: '3.8'

services:
  scrimhub-database:
    container_name: scrimhub-database
    restart: always
    build:
      context: ./docker
      dockerfile: Dockerfile.postgres.dev
    env_file:
      - ./.env
    ports:
      - 5432:5432
    volumes:
      - database-data:/var/lib/postgresql/data/
    networks:
      - app

  scrimhub-client:
    container_name: scrimhub-client
    restart: always
    stdin_open: true
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.client.dev
    env_file:
      - ./.env
    volumes:
      - .:/usr/src/app/
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    ports:
      - 3000:3000
      - 5555:5555 # Prisma Studio
    expose:
      - 3000
      - 5555
    depends_on:
      - scrimhub-database
    networks:
      - app

volumes:
  database-data:
    name: scrimhub-postgres-data

networks:
  app:
    name: scrimhub-app
    driver: bridge