import React from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import ScrimsBar from 'components/scrimsBar'
import Login from 'components/login'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <ScrimsBar />
        <Login />
      </main>
    </div>
  )
}

export default Home
