import type { NextPage } from 'next'
import Head from 'next/head'
import { useQuery, gql } from '@apollo/client'

const GET_USERS = gql`
  {
    users {
      id
      displayName
    }
  }
`

const Home: NextPage = () => {
  const { loading, error, data } = useQuery(GET_USERS)
  if (loading) return <p>Loading...</p>
  if (error) return <p>Error :</p>
  console.log(data)

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main></main>
    </div>
  )
}

export default Home
